-- Tabela de Produtos para LS Variedades
CREATE TABLE public.ls_products (
    id bigint generated by default as identity primary key,
    name text not null,
    description text,
    category text not null,
    price numeric(10,2) not null,
    image_data text, -- Pode ser uma URL ou uma string Base64 da imagem
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Tabela de Pedidos
CREATE TABLE public.ls_orders (
    id bigint generated by default as identity primary key,
    delivery_address jsonb not null, -- Rua, número, bairro, cidade
    payment_method text not null,
    total numeric(10,2) not null,
    items jsonb not null, -- Array de produtos comprados com quantidade
    status text default 'pendente',
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Desativar RLS (Row Level Security) temporariamente para facilitar o desenvolvimento
-- NOTA: Em produção, o ideal é ativar isso e criar políticas de segurança!
ALTER TABLE public.ls_products DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.ls_orders DISABLE ROW LEVEL SECURITY;

-- Opcional: Inserir os produtos padrão
INSERT INTO public.ls_products (name, description, category, price, image_data) VALUES
('Sérum Revitalizante Facial', 'Hidratação profunda para brilho diário.', 'feminino', 129.90, 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=60'),
('Hidratante Corporal Pêssego', 'Pele macia com toque aveludado.', 'feminino', 89.90, 'https://images.unsplash.com/photo-1615397323114-18e38d97e748?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=60'),
('Loção Pós-Barba Refrescante', 'Acalma a pele após o barbear.', 'masculino', 75.50, 'https://images.unsplash.com/photo-1629198688000-71f23e745b6e?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=60'),
('Balm para Barba', 'Fios alinhados e hidratados.', 'masculino', 65.00, 'https://images.unsplash.com/photo-1599305090598-fe179d501227?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=60');
